"""
PDF 생성 서비스.
마크다운 텍스트를 ReportLab을 이용해 PDF 바이트로 변환한다.
한글 지원을 위해 static/fonts/ 에 저장된 Noto Sans KR 폰트를 사용한다.
폰트 파일이 없으면 Helvetica(영문 전용)로 폴백한다.
"""
import io
import logging
from datetime import datetime, timezone, timedelta
from pathlib import Path

import markdown
from bs4 import BeautifulSoup
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    PageBreak, Paragraph, Preformatted, SimpleDocTemplate, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

logger = logging.getLogger("deepresearch.pdf")

_FONTS_DIR = Path(__file__).parent.parent / "static" / "fonts"


def _setup_fonts() -> tuple[str, str, str]:
    """
    사용할 폰트를 설정하고 (본문, 굵게, 기울임) 이름을 반환한다.
    static/fonts/ 의 Noto Sans KR 사용, 파일 없으면 Helvetica로 폴백한다.
    """
    reg_path = _FONTS_DIR / "NotoSansKR-Regular.ttf"
    bold_path = _FONTS_DIR / "NotoSansKR-Bold.ttf"

    if reg_path.exists() and bold_path.exists():
        try:
            pdfmetrics.registerFont(TTFont("NotoSansKR", str(reg_path)))
            pdfmetrics.registerFont(TTFont("NotoSansKR-Bold", str(bold_path)))
            # 기울임꼴은 별도 파일 없으므로 일반체로 대체
            pdfmetrics.registerFont(TTFont("NotoSansKR-Italic", str(reg_path)))
            logger.info("Noto Sans KR 폰트 등록 완료 (한글 지원)")
            return "NotoSansKR", "NotoSansKR-Bold", "NotoSansKR-Italic"
        except Exception as e:
            logger.warning(f"Noto Sans KR 등록 실패, Helvetica로 폴백: {e}")

    logger.warning("Helvetica 폴백 사용 — 한글이 PDF에서 깨질 수 있음")
    return "Helvetica", "Helvetica-Bold", "Helvetica-Oblique"


# 모듈 로드 시 폰트 설정 (한 번만 실행)
_FONT, _BOLD, _ITALIC = _setup_fonts()


def generate_pdf(markdown_text: str, topic: str) -> bytes:
    """마크다운 텍스트를 PDF 바이트로 변환한다."""
    font, bold, italic = _FONT, _BOLD, _ITALIC

    styles = getSampleStyleSheet()
    styles["Title"].fontName = bold
    styles["Title"].fontSize = 24
    styles["Title"].alignment = TA_CENTER
    styles["Title"].spaceAfter = 20
    styles["Title"].textColor = colors.HexColor("#FF3CAC")

    styles["Heading1"].fontName = bold
    styles["Heading1"].fontSize = 18
    styles["Heading1"].alignment = TA_CENTER
    styles["Heading1"].spaceBefore = 20
    styles["Heading1"].spaceAfter = 10
    styles["Heading1"].textColor = colors.HexColor("#FF3CAC")

    styles["Heading2"].fontName = bold
    styles["Heading2"].fontSize = 16
    styles["Heading2"].alignment = TA_CENTER
    styles["Heading2"].spaceBefore = 15
    styles["Heading2"].spaceAfter = 8
    styles["Heading2"].textColor = colors.HexColor("#784BA0")

    styles["Heading3"].fontName = bold
    styles["Heading3"].fontSize = 14
    styles["Heading3"].spaceBefore = 10
    styles["Heading3"].spaceAfter = 6
    styles["Heading3"].textColor = colors.HexColor("#333333")

    styles["Normal"].fontName = font
    styles["Normal"].fontSize = 11
    styles["Normal"].leading = 14
    styles["Normal"].spaceAfter = 8
    styles["Normal"].alignment = TA_JUSTIFY

    styles["Code"].fontName = font
    styles["Code"].fontSize = 9
    styles["Code"].leading = 12
    styles["Code"].backColor = colors.HexColor("#f5f5f5")
    styles["Code"].textColor = colors.HexColor("#333333")

    styles.add(ParagraphStyle(
        name="ListItem",
        fontName=font,
        fontSize=11,
        leading=14,
        leftIndent=20,
    ))
    styles.add(ParagraphStyle(
        name="Caption",
        fontName=italic,
        fontSize=10,
        leading=12,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#666666"),
    ))

    html_content = markdown.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "nl2br"],
    )
    soup = BeautifulSoup(html_content, "html.parser")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=72, leftMargin=72,
        topMargin=65, bottomMargin=70,
    )

    story = []

    # 표지 페이지
    story.append(Spacer(1, 2.5 * inch))
    story.append(Paragraph("Research Report", styles["Title"]))
    story.append(Spacer(1, 0.4 * inch))
    story.append(Paragraph(topic, styles["Heading2"]))
    story.append(Spacer(1, 1.5 * inch))
    story.append(Paragraph("Generated by DeepResearch AI", styles["Caption"]))
    KST = timezone(timedelta(hours=9))
    story.append(Paragraph(datetime.now(KST).strftime("%B %d, %Y (%H:%M KST)"), styles["Caption"]))
    story.append(PageBreak())

    in_list = False
    list_items: list[str] = []

    def flush_list():
        """누적된 목록 항목을 테이블로 변환해 story에 추가."""
        nonlocal in_list, list_items
        if list_items:
            data = [[Paragraph(item, styles["ListItem"])] for item in list_items]
            t = Table(data, colWidths=[400])
            t.setStyle(TableStyle([
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 15),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ]))
            story.append(t)
            list_items = []
            in_list = False

    # HTML 요소를 순회하며 ReportLab 스토리 구성
    for el in soup.descendants:
        tag = getattr(el, "name", None)
        if tag == "h1":
            flush_list()
            story.append(PageBreak())
            story.append(Paragraph(el.text, styles["Heading1"]))
        elif tag == "h2":
            flush_list()
            story.append(PageBreak())
            story.append(Paragraph(el.text, styles["Heading2"]))
        elif tag == "h3":
            flush_list()
            story.append(Paragraph(el.text, styles["Heading3"]))
        elif tag == "p":
            if el.parent and el.parent.name == "pre":
                continue  # pre 블록 안의 p 태그는 아래 pre 처리에서 담당
            flush_list()
            story.append(Paragraph(el.text, styles["Normal"]))
        elif tag == "pre":
            flush_list()
            code = el.get_text().replace("<", "&lt;").replace(">", "&gt;")
            story.append(Spacer(1, 0.1 * inch))
            story.append(Preformatted(code, styles["Code"]))
            story.append(Spacer(1, 0.1 * inch))
        elif tag in ("ul", "ol"):
            in_list = True
        elif tag == "li" and in_list:
            list_items.append("• " + el.text)
        elif tag == "table":
            flush_list()
            rows = []
            for tr in el.find_all("tr"):
                row = [Paragraph(td.get_text(), styles["Normal"]) for td in tr.find_all(["td", "th"])]
                if row:
                    rows.append(row)
            if rows:
                col_w = 450 / len(rows[0])
                t = Table(rows, colWidths=[col_w] * len(rows[0]))
                t.setStyle(TableStyle([
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f2f2f2")),
                    ("FONTNAME", (0, 0), (-1, 0), bold),
                    ("BOTTOMPADDING", (0, 0), (-1, 0), 12),
                ]))
                story.append(t)

    flush_list()
    doc.build(story)
    return buf.getvalue()
